### ISSUE TITLE
T-Square extraction issue

### ISSUE THREAD

**Issue by ra4king** [weeks001/submission-fix#1]
Traceback (most recent call last):
  File "SubmissionFix.py", line 825, in <module>
    main(sys.argv)
  File "SubmissionFix.py", line 817, in main
    TSquare.execute(args.bulksubmission, args.path, args.move, args.csv, args.time)
  File "SubmissionFix.py", line 290, in execute
    manager.extractBulk(zipfile, directory=tempPath) 
  File "SubmissionFix.py", line 327, in extractBulk
    zfile.extract(filename, directory)
  File "/usr/local/lib/python2.7/zipfile.py", line 1028, in extract
    return self._extract_member(member, path, pwd)
  File "/usr/local/lib/python2.7/zipfile.py", line 1082, in _extract_member
    with self.open(member, pwd=pwd) as source, \
  File "/usr/local/lib/python2.7/zipfile.py", line 1010, in open
    close_fileobj=should_close)
  File "/usr/local/lib/python2.7/zipfile.py", line 526, in __init__
    self._decompressor = zlib.decompressobj(-15)
AttributeError: 'NoneType' object has no attribute 'decompressobj'

**Comment by weeks001** [comment]
It looks like you're using a version of Python without the zlib library installed. Not sure how that happened but you can probably get it through pip or another package manager. 

http://unix.stackexchange.com/questions/164517/nonetype-object-has-no-attribute-decompressobj-while-installing-bootstrap-se
